server:
  port: 8007

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/e_budgets
    username: postgres
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

management:
  tracing:
    sampling:
      probability: 1.0
      
resilience4j:
  circuitbreaker:
    instances:
      setBudgetCB:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 1
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        
  ratelimiter:
    instances:
      setBudgetRL:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 2s   
     