server:
   port: 9902
      
spring:
     datasource:
       url: jdbc:postgresql://localhost:5432/sgroups
       username: postgres
       password: pass
     jpa:
       hibernate:
         ddl-auto: update
       show-sql: true
       
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost



management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always



resilience4j:
  circuitbreaker:
    instances:
      createGroupCB:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        
  retry:
   instances:
      createGroupRetry:
         max-attempts: 3
         wait-duration: 5s
         
  
  ratelimiter:
    instances:
      createGroupRL:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 2s
            
         



